kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-storage #需要与上面创建的storageclass的名称一致
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi