FROM registry.cn-beijing.aliyuncs.com/yuncenliu/elasticsearch:7.7.0
MAINTAINER elasticsearch date from UTC by Asia/Shanghai "yuncenLiu@163.com"
ENV TZ Asia/Shanghai
COPY elasticsearch.yml /usr/share/elasticsearch/config/
# docker build --rm -t registry.cn-beijing.aliyuncs.com/yuncenliu/elasticsearch:define-7.7.0 .
