# kubectl get ipaddresspool -n metallb-system
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: localip-pool
  namespace: metallb-system
spec:
  addresses:
    # - 192.168.58.4-192.168.58.6  # Windows 环境
    # 不能用 node 节点
    - 192.168.58.100-192.168.58.110
  autoAssign: true
  avoidBuggyIPs: true
