apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-stateful-set
  labels:
    app: mariadb-stateful-set
spec:
  replicas: 1
  serviceName: mariadb-headless-service
  template:
    metadata:
      name: mariadb-stateful-set
      labels:
        app: mariadb-stateful-set
    spec:
      containers:
        - name: mariadb-deploy
          image: mariadb:10.5.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"           # Mariadb root 密码
            - name: TZ
              value: Asia/Shanghai
              # 创建数据库
            - name: MYSQL_DATABASE
              value: yun
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
      restartPolicy: Always
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
  selector:
    matchLabels:
      app: mariadb-stateful-set
---
# headless service 无头服务
apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless-service
spec:
  selector:
    # 与 stateful set 中的 .spec.template.metadata.name 保持一致
    app: mariadb-stateful-set
  ports:
    - port: 3306
  clusterIP: None
