### 从 k8s-hostpath/mariadb-configmap-service.yml 修改而来，这里使用的是 hostpath 方式
### 改成使用 PV 方式
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  labels:
    app: mariadb-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: mariadb-deploy
      labels:
        app: mariadb-deploy
    spec:
      # label 操作，将 pod 固定在某一个固定的节点
      nodeSelector:
        mariadb: mariadb
      containers:
        - name: mariadb-deploy
          image: registry.cn-beijing.aliyuncs.com/yuncenliu/mariadb:10.5.2
          imagePullPolicy: Never
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              # 这是 root 用户密码
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mariadb-secret
            - name: TZ
              value: Asia/Shanghai
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - mountPath: /etc/mysql/mariadb.conf.d/   # 容器内的挂载目录
              name: yun-mariadb # 随便给一个名字，必须与 volumes.name 一致
            - mountPath: /var/lib/mysql # 容器内的挂载目录
              name: volume-mariadb
      restartPolicy: Always
      volumes:
        - name: yun-mariadb
          configMap: # 使用 kubectl get configmaps 查看 configmap
            name: mariabd-config
        - name: volume-mariadb
          persistentVolumeClaim:
            claimName: yun-mariadb-pvc
          # hostPath:
            # path: /root/container/mariadb-data
            #　type: Directory
  selector:
    matchLabels:
      app: mariadb-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb-deploy
  ports:
    - port: 3307
      targetPort: 3307
      nodePort: 30037
  type: NodePort
