apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yun-mariadb-pvc
  labels:
    app: yun-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
