apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiang-db
  labels:
    app: xiang-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiang-db
  template:
    metadata:
      labels:
        app: xiang-db
    spec:
      containers:
        - name: mysql
          image: registry.cn-beijing.aliyuncs.com/yuncenliu/lagou-mysql:5.7.44
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"  # 请替换为实际密码
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: xiang-db
  labels:
    app: xiang-db
spec:
  selector:
    app: xiang-db
  ports:
    - port: 3306      # 对集群内其他访问暴露端口
      targetPort: 3306
      nodePort: 30306   # 默认是 30000 - 32767 ，如果修改需要改 k8s 配置文件，官方不建议修改
  type: NodePort
  clusterIP: 10.100.6.100 # 固定 IP 地址

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xiang-app
  labels:
    app: xiang-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiang-app
  template:
    metadata:
      labels:
        app: xiang-app
    spec:
      initContainers:
        - name: wait-for-db
          image: registry.cn-beijing.aliyuncs.com/yuncenliu/busybox:1.32.0
          command:
            - sh
            - -c
            - |
              until nc -z -v -w30 10.100.6.100 3306; do
                echo "Waiting for database connection..."
                sleep 5
              done
              echo "Database is ready!"
      containers:
        - name: app
          image: registry.cn-beijing.aliyuncs.com/yuncenliu/lagou-app:1.4.2
          ports:
            - containerPort: 8082
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: aliyun-yuncen  # 阿里云私有镜像仓库的凭证

---
apiVersion: v1
kind: Service
metadata:
  name: xiang-app
spec:
  selector:
    app: xiang-app
  ports:
    - port: 8082      # 对集群内其他访问暴露端口
      targetPort: 8082
      nodePort: 30082   # 默认是 30000 - 32767 ，如果修改需要改 k8s 配置文件，官方不建议修改
  type: NodePort
  clusterIP: 10.100.6.101
