apiVersion: v1
kind: Pod
metadata:
  name: life-cle-test
  labels:
    app: life-cle-test
spec:
  containers:
    - name: life-cle-test
      image: registry.cn-beijing.aliyuncs.com/yuncenliu/busybox:1.32.0
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'sleep 3600']
      lifecycle:
        postStart:
          exec:
            command: ['mkdir', '-p', '/data/k8s/']
  imagePullSecrets:
    - name: aliyun-yuncen
  restartPolicy: Always
