version: '3'
services:
  pxc-01:
    image: registry.cn-beijing.aliyuncs.com/yuncenliu/mysql:percona-xtradb-cluster-5.7.30
    container_name: pxc-node-01
    privileged: true
    ports:
      - 3301:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - CLUSTER_NAME=pxc
    volumes:
      - /data/pxc-volume/pxc-v1:/var/lib/mysql
networks:
  default:
    external:
      name: pxc_network

