apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-fanout-a-dep
  name: simple-fanout-a-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-fanout-a-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-fanout-a-dep
    spec:
      containers:
      - image: ikubernetes/demoapp:v1.0
        name: demoapp
        resources: {}
status: {}
