apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yun-mariadb-nfs-pvc
  labels:
    app: yun-mariadb-nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-standard
  resources:
    requests:
      storage: 5Gi
