apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ip-demo
  labels:
    app: cluster-ip-demo
spec:
  replicas: 1
  template:
    metadata:
      name: cluster-ip-demo
      labels:
        # 对应 service.spec.selector.app
        app: cluster-ip-demo
    spec:
      containers:
        - name: cluster-ip-demo
          image: registry.cn-beijing.aliyuncs.com/yuncenliu/tomcat:9.0.20-jre8-alpine
          imagePullPolicy: IfNotPresent
          # 对集群内，暴露 8080 端口
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: cluster-ip-demo
# 多种资源，用 --- 隔开
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
spec:
  selector:
    # 对应 deployment.spec.template.metadata.labels.app
    app: cluster-ip-demo
  ports:
    - port: 8080
  type: ClusterIP
  clusterIP: 10.100.6.50