apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodename-demo
  labels:
    app: nginx-nodename-demo
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-nodename-demo
      labels:
        # 对应 service.spec.selector.app
        app: nginx-nodename-demo
    spec:
      nodeName: k8s-node-01
      imagePullSecrets:
        - name: aliyun-yuncen
      containers:
        - name: nginx-nodename-demo
          image: registry.cn-beijing.aliyuncs.com/yuncenliu/nginx:1.19.2-alpine
          imagePullPolicy: IfNotPresent
          # 对集群内，暴露 8080 端口
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: nginx-nodename-demo
# 多种资源，用 --- 隔开
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
spec:
  selector:
    # 对应 deployment.spec.template.metadata.labels.app
    app: nginx-nodename-demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort