version: '3'
services:
  pxc-02:
    image: registry.cn-beijing.aliyuncs.com/yuncenliu/mysql:percona-xtradb-cluster-5.7.30
    container_name: pxc-node-02
    privileged: true
    ports:
      - 3302:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - CLUSTER_NAME=pxc
      # 相对于 01 节点，新增了一个
      - CLUSTER_JOIN=pxc-node-01
    volumes:
      - /data/pxc-volume/pxc-v2:/var/lib/mysql
  pxc-03:
    image: registry.cn-beijing.aliyuncs.com/yuncenliu/mysql:percona-xtradb-cluster-5.7.30
    container_name: pxc-node-03
    privileged: true
    ports:
      - 3303:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - CLUSTER_NAME=pxc
      # 相对于 01 节点，新增了一个
      - CLUSTER_JOIN=pxc-node-01
    volumes:
      - /data/pxc-volume/pxc-v3:/var/lib/mysql
networks:
  default:
    external:
      name: pxc_network
