apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xiang-auth-deployment
  name: xiang-auth-deployment
  namespace: xiang-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiang-auth-deployment
  strategy: { }
  template:
    metadata:
      labels:
        app: xiang-auth-deployment
    spec:
      # 拉取镜像需要使用到的secret
      imagePullSecrets:
        - name: aliyun-yuncen
      containers:
        - env:
            # 运行时环境，引用一开始创建的configmap，值为prod
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: spring-profile-cm
                  key: spring-profiles-active
            # 设置一些jvm调优参数
            - name: JAVA_OPTION
              value: "-Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:+PrintGCDetails -Xloggc:/var/log/devops-example.gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC"
            - name: XMX
              value: "128m"
            - name: XMS
              value: "128m"
            - name: XMN
              value: "64m"
          image: registry.cn-beijing.aliyuncs.com/yuncenliu/xiang-cloud-service:auth-1.0
          name: auth
          # 存活探针
          livenessProbe:
            # 发送http get请求到8080端口的/actuator/health路径检查pod是否健康
            httpGet:
              path: /actuator/health
              port: 8100
              scheme: HTTP
            # pod初始化完毕20秒之后再开始
            initialDelaySeconds: 20
            # 之后每10秒进行一次健康检查
            periodSeconds: 10
          ports:
            - containerPort: 8100
          resources: { }

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: xiang-auth-deployment
  name: xiang-auth-svc
  namespace: xiang-cloud
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: xiang-auth-deployment
  type: ClusterIP
